[package]
name = "sm_connect"
version = "1.6.1"
edition = "2024"
description = "A TUI tool to connect to AWS EC2 instances via SSM Session Manager"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-ec2 = "1.223.0"
tokio = { version = "1.52.1", features = ["full"] }
ratatui = { version = "0.30.0", features = ["all-widgets"]}
anyhow = "1.0.102"
crossterm = "0.29.0"
signal-hook = "0.4.4"
aws-config = "1.8.16"
configparser = "3.1.0"
home = "0.5.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
clap = { version = "4.6.1", features = ["derive"] }
russh = "0.60"
russh-sftp = "2.1"
aws-sdk-ecs = "1.125.0"
